server:
  port: 8001
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://35.223.54.93:5432/guerra
    username: postgres
    password: informatica2021
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect